/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppointmentUpdateManyWithoutDoctorsInput } from "./AppointmentUpdateManyWithoutDoctorsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { MedicalHistoryUpdateManyWithoutDoctorsInput } from "./MedicalHistoryUpdateManyWithoutDoctorsInput";
import { EnumDoctorTypeField } from "./EnumDoctorTypeField";

@InputType()
class DoctorUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactInformation?: string | null;

  @ApiProperty({
    required: false,
    type: () => MedicalHistoryUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => MedicalHistoryUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => MedicalHistoryUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  medicalHistories?: MedicalHistoryUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specialty?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumDoctorTypeField,
  })
  @IsEnum(EnumDoctorTypeField)
  @IsOptional()
  @Field(() => EnumDoctorTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;
}

export { DoctorUpdateInput as DoctorUpdateInput };
