/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MedicalHistory } from "./MedicalHistory";
import { MedicalHistoryCountArgs } from "./MedicalHistoryCountArgs";
import { MedicalHistoryFindManyArgs } from "./MedicalHistoryFindManyArgs";
import { MedicalHistoryFindUniqueArgs } from "./MedicalHistoryFindUniqueArgs";
import { CreateMedicalHistoryArgs } from "./CreateMedicalHistoryArgs";
import { UpdateMedicalHistoryArgs } from "./UpdateMedicalHistoryArgs";
import { DeleteMedicalHistoryArgs } from "./DeleteMedicalHistoryArgs";
import { Doctor } from "../../doctor/base/Doctor";
import { Patient } from "../../patient/base/Patient";
import { MedicalHistoryService } from "../medicalHistory.service";
@graphql.Resolver(() => MedicalHistory)
export class MedicalHistoryResolverBase {
  constructor(protected readonly service: MedicalHistoryService) {}

  async _medicalHistoriesMeta(
    @graphql.Args() args: MedicalHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MedicalHistory])
  async medicalHistories(
    @graphql.Args() args: MedicalHistoryFindManyArgs
  ): Promise<MedicalHistory[]> {
    return this.service.medicalHistories(args);
  }

  @graphql.Query(() => MedicalHistory, { nullable: true })
  async medicalHistory(
    @graphql.Args() args: MedicalHistoryFindUniqueArgs
  ): Promise<MedicalHistory | null> {
    const result = await this.service.medicalHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MedicalHistory)
  async createMedicalHistory(
    @graphql.Args() args: CreateMedicalHistoryArgs
  ): Promise<MedicalHistory> {
    return await this.service.createMedicalHistory({
      ...args,
      data: {
        ...args.data,

        doctor: args.data.doctor
          ? {
              connect: args.data.doctor,
            }
          : undefined,

        patient: args.data.patient
          ? {
              connect: args.data.patient,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => MedicalHistory)
  async updateMedicalHistory(
    @graphql.Args() args: UpdateMedicalHistoryArgs
  ): Promise<MedicalHistory | null> {
    try {
      return await this.service.updateMedicalHistory({
        ...args,
        data: {
          ...args.data,

          doctor: args.data.doctor
            ? {
                connect: args.data.doctor,
              }
            : undefined,

          patient: args.data.patient
            ? {
                connect: args.data.patient,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MedicalHistory)
  async deleteMedicalHistory(
    @graphql.Args() args: DeleteMedicalHistoryArgs
  ): Promise<MedicalHistory | null> {
    try {
      return await this.service.deleteMedicalHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Doctor, {
    nullable: true,
    name: "doctor",
  })
  async getDoctor(
    @graphql.Parent() parent: MedicalHistory
  ): Promise<Doctor | null> {
    const result = await this.service.getDoctor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Patient, {
    nullable: true,
    name: "patient",
  })
  async getPatient(
    @graphql.Parent() parent: MedicalHistory
  ): Promise<Patient | null> {
    const result = await this.service.getPatient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
