/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Patient as PrismaPatient,
  Appointment as PrismaAppointment,
  MedicalHistory as PrismaMedicalHistory,
  Medication as PrismaMedication,
  Notification as PrismaNotification,
} from "@prisma/client";

export class PatientServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PatientCountArgs, "select">): Promise<number> {
    return this.prisma.patient.count(args);
  }

  async patients(args: Prisma.PatientFindManyArgs): Promise<PrismaPatient[]> {
    return this.prisma.patient.findMany(args);
  }
  async patient(
    args: Prisma.PatientFindUniqueArgs
  ): Promise<PrismaPatient | null> {
    return this.prisma.patient.findUnique(args);
  }
  async createPatient(args: Prisma.PatientCreateArgs): Promise<PrismaPatient> {
    return this.prisma.patient.create(args);
  }
  async updatePatient(args: Prisma.PatientUpdateArgs): Promise<PrismaPatient> {
    return this.prisma.patient.update(args);
  }
  async deletePatient(args: Prisma.PatientDeleteArgs): Promise<PrismaPatient> {
    return this.prisma.patient.delete(args);
  }

  async findAppointments(
    parentId: string,
    args: Prisma.AppointmentFindManyArgs
  ): Promise<PrismaAppointment[]> {
    return this.prisma.patient
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .appointments(args);
  }

  async findMedicalHistories(
    parentId: string,
    args: Prisma.MedicalHistoryFindManyArgs
  ): Promise<PrismaMedicalHistory[]> {
    return this.prisma.patient
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .medicalHistories(args);
  }

  async findMedications(
    parentId: string,
    args: Prisma.MedicationFindManyArgs
  ): Promise<PrismaMedication[]> {
    return this.prisma.patient
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .medications(args);
  }

  async findNotifications(
    parentId: string,
    args: Prisma.NotificationFindManyArgs
  ): Promise<PrismaNotification[]> {
    return this.prisma.patient
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .notifications(args);
  }
}
